name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs daily

jobs:
  fetch-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history

      - name: Fetch README from the specified repository
        run: |
          curl -o README.md https://raw.githubusercontent.com/FelixKnutsen/FelixKnutsen/main/README.md

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/FelixKnutsen/portfolio.git
          git fetch origin
          git reset --hard origin/main
          git add README.md
          git commit -m "Update README from FelixKnutsen repository"
          git push origin main
